#!/bin/bash
if [ "$#" -ne 1 ]; then
	echo "Usage: get-snapshot-uuid nodename"
	exit 1;
fi

case "$1" in
	"debian-stable")
		echo "a1ce9ba9-82fb-7b2e-376e-74f63b9f24ad";;

	"debian-oldstable")
		echo "95112ce4-b713-edcc-186e-4bda92e44b30";;

	"ubuntu-oldlts")
		echo "dad5f403-fbbb-8da8-b7f4-654745f19483";;

	*)
		echo "Invalid node name";
		exit 1;;
esac
