#!/bin/bash
if [ "$#" -ne 1 ]; then
	echo "Usage: get-vm-uuid nodename"
	exit 1;
fi

# updated 2026-04-25 for new UUIDs
case "$1" in

	"arch")
		echo "a41ad7bb-8e67-ff50-dedf-c86a10a569c9";;

	"debian-stable")
		echo "9b78594a-b9d3-09cf-6e28-4d9ec6d72077";;

	"debian-oldstable")
		echo "ca3722cc-8fa0-355c-c6c9-b8ef8b7f4d0f";;

	"fedora")
		echo "7f2bbfa4-fbb7-998d-03c4-fa8c9bca17d9";;

	"ubuntu-oldlts")
		echo "81d8224d-c35a-ec9c-5a7f-34dd4c40867f";;

	"ubuntu-lts-1")
		echo "06ffa976-5cef-894e-c4ab-7774080f2f67";;

	"ubuntu-lts-2")
		echo "b2cfe297-5571-2b79-30bc-bf85af9b5709";;

	"win11")
		echo "a7bf431e-0eef-dff2-0b57-1bf9e5992e90";;

	*)
		echo "Invalid node name";
		exit 1;;
esac
