#!/bin/bash

# slurm prolog script has no search path by default
# we also need to say "print" for stdout messages to go to the srun output
PATH=/usr/local/bin:/usr/bin:/bin:/home/ci/scopehal-ci-scripts/vm
if [ "$SLURM_NTASKS" -ne 1 ]; then
	echo "print Only single-node jobs are supported"
	exit 1;
fi

# VM configuration
NODE=$SLURM_JOB_NODELIST
VM_UUID=`get-vm-uuid $NODE` || (echo "invalid node ID"; exit 1;)
VM_HOSTNAME=$NODE.cidmz.poulsbo.antikernel.net

# Spawn the worker VM
echo "print Starting worker node $NODE...";
xo-cli vm.start id=$VM_UUID > /dev/null

# Wait for the VM to boot
echo "print Waiting for worker $NODE to boot...";
while : ; do
	#echo "SSH poll...";
	if ssh -o ConnectTimeout=5 $VM_HOSTNAME hostname > /dev/null 2> /dev/null
	then
		break
	fi
done
echo "print $VM_HOSTNAME is up"
