#!/bin/bash

# slurm epilog script has no search path by default
#seems we cannot print anything from epilog, need to redirect to a file
PATH=/usr/local/bin:/usr/bin:/bin:/home/ci/scopehal-ci-scripts/vm

# VM configuration
NODE=$SLURM_JOB_NODELIST

#No VM stuff needed at all for postprocessing, that runs on the host
if [ "$NODE" == "postprocess" ]; then

exit;

#Special case the MacOS VM
elif [ "$NODE" == "macos" ]; then

	# Set this as needed for $NODE
	RUNNER_NAME="ci-macos-runner"

	# NOTE: need to add app control permissions as described by alanb-sony https://github.com/utmapp/UTM/issues/5377
	# or this won't work
	MAC_HOST=cheddar.lab.poulsbo.antikernel.net
	echo "Shutting down runner...";
	ssh azonenberg@$MAC_HOST /usr/local/bin/utmctl stop $RUNNER_NAME
	echo "Wiping runner...";
	ssh azonenberg@$MAC_HOST /usr/local/bin/utmctl delete $RUNNER_NAME

# Default case: assume it's an xcp-ng VM
else
	VM_UUID=`get-vm-uuid $NODE` || (echo "invalid node ID"; exit 1;)
	SNAPSHOT_UUID=`get-snapshot-uuid $NODE` || (echo "invalid node ID"; exit 1;)

	# Shut it down and wipe it
	echo "Shutting down runner...";
	xo-cli vm.stop id=$VM_UUID > /dev/null
	echo "Wiping runner...";
	xo-cli vm.revert snapshot=$SNAPSHOT_UUID > /dev/null
fi
