SlurmctldHost=ci-orchestrator
AuthType=auth/slurm
CredType=cred/slurm
ClusterName=ci
SlurmUser=slurm
SlurmdUser=root
StateSaveLocation=/var/spool/slurm
SlurmdPidFile=/var/run/slurmd.%n.pid
SlurmctldLogFile=/var/log/slurm/slurmctld.log
AccountingStorageHost=localhost
AccountingStorageType=accounting_storage/slurmdbd

# Log job completions

# large timeout because prologue script can take a while to spawn the VM and get it runnable
BatchStartTimeout=45
PrologEpilogTimeout=45
PrologFlags=serial

# no timeout after a job finishes? equal KillWait+2
CompleteWait=0

TaskProlog=/home/ci/scopehal-ci-scripts/slurm/prolog.sh
TaskEpilog=/home/ci/scopehal-ci-scripts/slurm/epilog.sh

# We treat GPUs as "licenses" since they're a pool of resources all VMs have to share
# We currently have three RTX 3050s in the server
# Also allow each one to be requested individually by PCI path
# We also create a license for all CI jobs running on sanquentin and the mac mini
# so we can manage vCPU oversubscription
Licenses=nvidia3050_51:1,nvidia3050_52:1,nvidia3050_8a:1,sanquentin:5,macmini:1

# List of nodes
NodeName=debian-stable NodeHostname=ci-orchestrator CPUs=1 Features=debian,debian-13,nvidia Port=9000
NodeName=debian-oldstable NodeHostname=ci-orchestrator CPUs=1 Features=debian,debian-12,nvidia Port=9001
NodeName=ubuntu-oldlts NodeHostname=ci-orchestrator CPUs=1 Features=ubuntu,ubuntu-24-04,nvidia Port=9002
NodeName=ubuntu-lts-1 NodeHostname=ci-orchestrator CPUs=1 Features=ubuntu,ubuntu-26-04 Port=9003
NodeName=win11 NodeHostname=ci-orchestrator CPUs=1 Features=windows,win11,nvidia Port=9004
NodeName=arch NodeHostname=ci-orchestrator CPUs=1 Features=arch,nvidia Port=9005
NodeName=fedora NodeHostname=ci-orchestrator CPUs=1 Features=fedora Port=9006
NodeName=macos NodeHostname=ci-orchestrator CPUs=1 Features=macos Port=9007
NodeName=ubuntu-lts-2 NodeHostname=ci-orchestrator CPUs=1 Features=ubuntu,ubuntu-26-04 Port=9008
NodeName=postprocess NodeHostname=ci-orchestrator CPUs=1 Port=9009
NodeName=debian-stable-aarch64 NodeHostname=ci-orchestrator CPUs=1 Features=debian,debian-13 Port=9010

# List of partitions
#PartitionName=debian Nodes=debian-stable,debian-oldstable
PartitionName=debian-stable-aarch64 Nodes=debian-stable-aarch64
PartitionName=debian-stable Nodes=debian-stable
PartitionName=debian-oldstable Nodes=debian-oldstable

#PartitionName=ubuntu Nodes=ubuntu-oldlts,ubuntu-lts
PartitionName=ubuntu-oldlts Nodes=ubuntu-oldlts
PartitionName=ubuntu-lts Nodes=ubuntu-lts-[1-2]

PartitionName=win11 Nodes=win11

PartitionName=arch Nodes=arch

PartitionName=fedora Nodes=fedora

PartitionName=macos Nodes=macos

PartitionName=postprocess Nodes=postprocess
