SlurmctldHost=ci-orchestrator
AuthType=auth/slurm
CredType=cred/slurm
ClusterName=ci
SlurmUser=slurm
SlurmdUser=root
StateSaveLocation=/var/spool/slurm

# large timeout because prologue script can take a while to spawn the VM and get it runnable
BatchStartTimeout=45
PrologEpilogTimeout=45
PrologFlags=serial

# no timeout after a job finishes? equal KillWait+2
CompleteWait=0

TaskProlog=/home/ci/scopehal-ci-scripts/slurm/prolog.sh
TaskEpilog=/home/ci/scopehal-ci-scripts/slurm/epilog.sh

# List of nodes
NodeName=debian-stable NodeHostname=ci-orchestrator CPUs=1 Features=debian,debian-13,nvidia,Port=9000
NodeName=debian-oldstable NodeHostname=ci-orchestrator CPUs=1 Features=debian,debian-12,nvidia,Port=9001

# List of partitions
PartitionName=debian Nodes=debian-stable,debian-oldstable
PartitionName=debian-stable Nodes=debian-stable
PartitionName=debian-oldstable Nodes=debian-oldstable
