# NOTE: this file needs to be copied (not symlinked) to /etc/slurm and chown'd slurm:slurm, chmod 600
DbdHost=localhost
DebugLevelSyslog=info
SlurmUser=slurm
StorageHost=localhost
StorageLoc=slurmacct
StorageUser=slurm
StorageType=accounting_storage/mysql
