SlurmctldHost=ci-orchestrator
AuthType=auth/slurm
CredType=cred/slurm
ClusterName=ci
SlurmUser=slurm
SlurmdUser=root
StateSaveLocation=/var/spool/slurm
SlurmdPidFile=/var/run/slurmd.%n.pid

# Log job completions

# large timeout because prologue script can take a while to spawn the VM and get it runnable
BatchStartTimeout=45
PrologEpilogTimeout=45
PrologFlags=serial

# no timeout after a job finishes? equal KillWait+2
CompleteWait=0

TaskProlog=/home/ci/scopehal-ci-scripts/slurm/prolog.sh
TaskEpilog=/home/ci/scopehal-ci-scripts/slurm/epilog.sh

# We treat GPUs as "licenses" since they're a pool of resources all VMs have to share
# We currently have three GTX 1630s in the server
# Also allow each one to be requested individually by PCI path since some VMs prefer that
Licenses=nvidia1630:3,nvidia1630_18:1

# List of nodes
NodeName=debian-stable NodeHostname=ci-orchestrator CPUs=1 Features=debian,debian-13,nvidia Port=9000
NodeName=debian-oldstable NodeHostname=ci-orchestrator CPUs=1 Features=debian,debian-12 Port=9001
NodeName=ubuntu-oldlts NodeHostname=ci-orchestrator CPUs=1 Features=ubuntu,ubuntu-24-04 Port=9002

# List of partitions
PartitionName=debian Nodes=debian-stable,debian-oldstable
PartitionName=debian-stable Nodes=debian-stable
PartitionName=debian-oldstable Nodes=debian-oldstable

PartitionName=ubuntu Nodes=ubuntu-oldlts
PartitionName=ubuntu-oldlts Nodes=ubuntu-oldlts
